### ISSUE TITLE
Unable to parse line...

### ISSUE THREAD

**Issue by hack1nt0** [dato-code/SFrame#101]
When I used SFrame to read_csv, I came across error below:

=======

PROGRESS: Unable to parse line ""###0000","{}","{""-2sxY5OvAJh4UT3w"":""不vvv""}""

PROGRESS: Unable to parse line ""**666996","{}","{""uFx1XYq5tjyFt8--"":""八八\\\\\\\\""}""

=====

Then What's wrong with those lines? could somebody tell me how the SFrame to parse line?

By the Way, the file containing these lines are generated from SFrame itself by save method.

Thank you!

**Comment by esoroush** [comment]
Hi There,

Did you save the sframe as a csv file or using the default save format? This looks like a binary format to me.

**Comment by ylow** [comment]
If you use the regular "save" method, it saves in a binary format. In which case you load it with 
```
gl.SFrame('[path]')
```
