### ISSUE TITLE
New version ?

### ISSUE THREAD

**Issue by sb2nov** [dato-code/SFrame#120]
The current released version is 168 commits behind, do you have plans to release a newer version of SFrame ?

**Comment by znation** [comment]
@sb2nov Yes, it will be coming soon! Sorry for the delay; after open sourcing we are still working on some internal processes for keeping code in sync between open and closed source codebases and automating the release processes of each. You should expect to see a new release of SFrame on PyPI in several weeks.

**Comment by TobyRoseman** [comment]
@sb2nov - We've issued a new release. You can upgrade by `pip install -U SFrame`. See our github [release page](https://github.com/dato-code/SFrame/releases/tag/v1.8) for more information.

**Comment by sb2nov** [comment]
@TobyRoseman thank you so much.
