### ISSUE TITLE
Configure with a gcc toolchain download from the dato(amazon) fails > ERROR 403: Forbidden

### ISSUE THREAD

**Issue by Advaya-Labs** [dato-code/SFrame#133]
Hi,
I  tried installing using the dato gcc tool chain on my CentOS 6.7 as per instructions : 
 **./configure --toolchain=https://s3-us-west-2.amazonaws.com/dato-deps/1/dato_deps_linux_gcc_4.9.2.tar.gz**

**This configuration fails with the following error:** 
Downloading dato_deps_linux_gcc_4.9.2.tar.gz from https://s3-us-west-2.amazonaws.com/dato-deps/1/dato_deps_linux_gcc_4.9.2.tar.gz ...
--2016-01-13 18:58:04--  https://s3-us-west-2.amazonaws.com/dato-deps/1/dato_deps_linux_gcc_4.9.2.tar.gz
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 54.231.162.24
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.162.24|:443... connected.
**HTTP request sent, awaiting response... 403 Forbidden
2016-01-13 18:58:04 ERROR 403: Forbidden.**

Please help me in this regard.
Thanks!

**Comment by TobyRoseman** [comment]
That's a really old version of dato-deps. Just run `configure` without any parameters and it will pick up the most recent version.

That should fix your problem. Let me know if you run into any other issues.

**Comment by Advaya-Labs** [comment]
Hi Toby,
Just ran configure without any parameters and ran into the issue listed below . The configure exits midway (probably due to the very old gcc 4.4.7 toolchain on CentOS 6.7. Searched online to resolve this but couldn't)

/testSFrame/deps/local/bin/cmake: /usr/lib64/libstdc++.so.6: version  ** `GLIBCXX_3.4.14' not found **(required by /testSFrame/deps/local/bin/cmake)
/testSFrame/deps/local/bin/cmake: /usr/lib64/libstdc++.so.6: version  ** `GLIBCXX_3.4.15' not found ** (required by /testSFrame/deps/local/bin/cmake)

**Comment by ylow** [comment]
Hi,

For Linux we bootstrap an entire toolchain with a compiler and everything. But of course, that means that to run cmake itself may require a newer version of the stdc++ library than the system has. This can be resolved by running the following command first:
```
export LD_LIBRARY_PATH=[sframe_directory]/deps/local/lib64
```
substituting sframe_directory with your checkout directory.
```

**Comment by Advaya-Labs** [comment]
Thank You!  This worked!
Although i ran into issue with the build due to zlib, i was able to resolve it due to the last suggestion posted at http://forum.dato.com/discussion/1125/importerror-libunity-shared-so-undefined-symbol-gzopen64

Thank you for the support! :)
