### ISSUE TITLE
The output of a sframe[row] is a dict, which messes up the output

### ISSUE THREAD

**Issue by znation** [dato-code/SFrame#136]
Being new to the platform, I wanted to look at a row of data and did:

![image](https://cloud.githubusercontent.com/assets/3951218/12184014/765c8604-b547-11e5-834b-1723dcc2861f.png)

Which is great, except the columns are out of order from the original SFrame, which made me think I had a bug, and kept looking for a while. Then I decided to save the SFrame to disk (as CSV), and BOOM everything is as expected.

This is very annoying that the columns are not in the order displayed. Hoyt says that we could use an ordereddict and it would fix this.

**Comment by ylow** [comment]
That's quirky and seems to serve no purpose other than presentation. The OrderedDict is strictly slower than the dict and is non-native (it is implemented in Python. See collections.py)

The dict is at least a common type and should be used preferably I would think.
