### ISSUE TITLE
Missing special methods for SArray in the Python API

### ISSUE THREAD

**Issue by shoyer** [dato-code/SFrame#14]
I just tried playing around with SFrame, and noticed that you haven't added some useful special methods:

- `__abs__` corresponds to `abs(sf['x'])`
- `__neg__` corresponds to `-sf['x']`
- `__pos__` corresponds to `+sf['x']`
- `__pow__` corresponds to `sf['x'] ** 2`

These are pretty low hanging fruit but quite useful for compatibility with standard Python idioms.

**Comment by hoytak** [comment]
Resolved by https://github.com/dato-code/SFrame/pull/22.
