### ISSUE TITLE
how to read csv with mutiple list fields?

### ISSUE THREAD

**Issue by hiyijian** [dato-code/SFrame#145]
my csv file, one single line with TAB sep:
--------------------test.csv-------------------------
xxx	[1,2,3]	[1,2,3]

import sframe as sf
sf.SFrame.read_csv("./test", delimiter="\t", column_type_hints=[str, list, list], header=False)

And I get error like this:
RuntimeError: Runtime Exception. column_type_hints has different size from actual number of columns: column_type_hints.size()=3;number of columns=4

pls help.
Thanks!

**Comment by ylow** [comment]
Ooo. That seems like a bug. Oddly enough it works if it is comma separated. I will take a look at it shortly.

**Comment by hiyijian** [comment]
@ylow  Thank you.
