### ISSUE TITLE
run_cpp_tests only work if C++ tests already built

### ISSUE THREAD

**Issue by TobyRoseman** [dato-code/SFrame#154]
Building the C++ tests doesn't happen when you build everything else. If you try to run `./oss_local_scripts/run_cpp_tests.py` when you have not built the C++ test, you get a super unhelpful error message.

**Comment by ylow** [comment]
Yeah.  This is expected. run_cpp_tests just runs any existing .cxxtest files, hashing them into a location so that identical tests don't get rerun again. It doesn't actually know how to build the tests.
