### ISSUE TITLE
SArray boolean logic doesn't work for missing values

### ISSUE THREAD

**Issue by papayawarrior** [dato-code/SFrame#178]
Missing values seem to propagate into boolean masks when they shouldn't. 

```python
>>> import graphlab as gl
>>> sf = gl.SFrame({'a': [1, None, 3]})
>>> mask = sf['a'] == 3
>>> mask
dtype: int
Rows: 3
[0, None, 1]
```

My expected output is `[0, 0, 1]`.

This was reported initially on the Dato forum, at http://forum.dato.com/discussion/1723/indexing-sframes-with-logical-or-condition

**Comment by MatthewWest** [comment]
Working on this...
