### ISSUE TITLE
Lambda workers cannot not start

### ISSUE THREAD

**Issue by nikhilrj** [dato-code/SFrame#221]
Running the following code causes the "lambda worker" runtime exception as described [here](http://forum.dato.com/discussion/1499/graphlab-create-using-anaconda-ipython-notebook-lambda-workers-did-not-start).

```
import sframe as sf
print sf.SArray(range(1000)).apply(lambda x: x).sum()
```
The error is as follows:

> RuntimeError: Runtime Exception. Cannot evaluate lambda. Lambda workers cannot not start.

According to the linked thread, this appears to be fixed in GraphLab. Do you have any guidance in fixing this with the SFrame package?

I'm running on Windows Server 2012 with SFrame 1.8.4.

Thanks!

**Comment by hoytak** [comment]
Hello @nikhilrj,

The code in SFrame is the same as that used for graphlab, so it appears this is a new issue.  Is there a chance you could test the graphlab installation to see if that fixes it for you? 

We've noticed a few errors in windows popping up with 1.8.4, and these seem mostly related to environment and configuration, and we're still getting to the bottom of these.  Windows gives us a lot less control over the runtime environment and library loading than linux or mac does, and tracking down these lambda worker issues has been a frustrating exercise of figuring out numerous corner cases.  

In your case, would it be possible to attach the log file?  This is printed at the beginning, right after the first command is run -- if you run 
```
import sframe
sframe.SArray(range(1000)).apply(lambda x:x).sum()
``` 
Then you should see the log file printed at the top, along with an error message. 

In addition, could you run 

```
import sframe
sframe.sys_util.test_pylambda_worker()
```

and tell me what the output is?

Thanks!
-- Hoyt

**Comment by nikhilrj** [comment]
Hi @hoytak,

I don't have a GraphLab license, so I won't be able to see if it's a potential fix. I've attached the log file. The output when running your second snippet is as follows:
[sframe_server_1457997251.log.0.0.txt](https://github.com/dato-code/SFrame/files/173019/sframe_server_1457997251.log.0.0.txt)

> C:\Users\nijogl>python
> Python 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 14:26:21) [MSC v.
> 1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> Anaconda is brought to you by Continuum Analytics.
> Please check out: http://continuum.io/thanks and https://anaconda.org
> >>> import sframe
> >>> sframe.sys_util.test_pylambda_worker()
> 
> Launch pylambda_worker process with simulated unity_server environment.
> Lambda worker args:
>   C:\Users\nijogl\Desktop\Anaconda\lib\site-packages\sframe\_scripts\_pylambda_w
> orker.pyc
> PyLambda script called with no IPC information; entering diagnostic mode.
>   sys.path[0] = C:\Users\nijogl\Desktop\Anaconda\python27.zip.
>   sys.path[1] = C:\Users\nijogl\Desktop\Anaconda\DLLs.
>   sys.path[2] = C:\Users\nijogl\Desktop\Anaconda\lib.
>   sys.path[3] = C:\Users\nijogl\Desktop\Anaconda\lib\plat-win.
>   sys.path[4] = C:\Users\nijogl\Desktop\Anaconda\lib\lib-tk.
>   sys.path[5] = C:\Users\nijogl\Desktop\Anaconda.
>   sys.path[6] = c:\users\nijogl\desktop\anaconda\lib\site-packages\sphinx-1.3.5-
> py2.7.egg.
>   sys.path[7] = c:\users\nijogl\desktop\anaconda\lib\site-packages\setuptools-19
> .6.2-py2.7.egg.
>   sys.path[8] = C:\Users\nijogl\Desktop\Anaconda\lib\site-packages.
>   sys.path[9] = C:\Users\nijogl\Desktop\Anaconda\lib\site-packages\cryptography-
> 1.0.2-py2.7-win-amd64.egg.
>   sys.path[10] = C:\Users\nijogl\Desktop\Anaconda\lib\site-packages\win32.
>   sys.path[11] = C:\Users\nijogl\Desktop\Anaconda\lib\site-packages\win32\lib.
>   sys.path[12] = C:\Users\nijogl\Desktop\Anaconda\lib\site-packages\Pythonwin.
>   sys.path[13] = C:\Users\nijogl\Desktop\Anaconda\lib\site-packages\IPython\exte
> nsions.
> Main program directory: C:\Users\nijogl\Desktop\Anaconda\lib\site-packages\sfram
> e.
> ←[1;33m1457997014 : DEBUG:    (operator():71): PID-17736: root_path = 'C:\Users\
> nijogl\Desktop\Anaconda\lib\site-packages\sframe'
> ←[0m←[1;33m1457997014 : DEBUG:    (operator():72): PID-17736: server_address = '
> debug'
> ←[0m←[1;33m1457997014 : DEBUG:    (operator():73): PID-17736: parend pid = 38312
> 
> ←[0m←[1;33m1457997014 : DEBUG:    (operator():77): PID-17736: Library function e
> ntered successfully.
> ←[0m1457997014 : INFO:     (pylambda_worker_main:80): Exiting dry run.
> ←[0mLambda process exited with code 1.
> >>>

**Comment by hoytak** [comment]
Okay, thank you.  This is really helpful.  Could you try running the following commands as well, and letting me know what the output is?

```
import os
os.environ["GRAPHLAB_LAMBDA_WORKER_DEBUG_MODE"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
import sframe
sframe.SArray(range(1000)).apply(lambda x: x).sum()
```

This should display quite a bit more debugging info.

Thanks!
-- Hoyt

**Comment by nikhilrj** [comment]
Here's the log file: 
[sframe_server_1457999482.log.0.0.txt](https://github.com/dato-code/SFrame/files/173045/sframe_server_1457999482.log.0.0.txt)


And the output:
> C:\Users\nijogl>python
> Python 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 14:26:21) [MSC v.
> 1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> Anaconda is brought to you by Continuum Analytics.
> Please check out: http://continuum.io/thanks and https://anaconda.org
> >>> import os
> >>> os.environ["GRAPHLAB_LAMBDA_WORKER_DEBUG_MODE"] = "1"
> >>> os.environ["OMP_NUM_THREADS"] = "1"
> >>> import sframe
> >>> sframe.SArray(range(1000)).apply(lambda x: x).sum()
> 2016-03-14 16:51:23,048 [INFO] sframe.cython.cy_server, 172: SFrame v1.8.4 start
> ed. Logging C:\Users\nijogl\AppData\Local\Temp\15\sframe_server_1457999482.log.0
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\nijogl\Desktop\Anaconda\lib\site-packages\sframe\data_structure
> s\sarray.py", line 1701, in apply
>     return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_undefined, see
> d))
>   File "C:\Users\nijogl\Desktop\Anaconda\lib\site-packages\sframe\cython\context
> .py", line 49, in __exit__
>     raise exc_type(exc_value)
> RuntimeError: Runtime Exception. Cannot evaluate lambda. Lambda workers cannot n
> ot start.
> 

Let me know if there's anything else you need!

**Comment by hoytak** [comment]
Ah, okay.  Sometimes the log messages in the lambda processes come through, and sometimes they do not (windows under the hood is ... difficult).  Could you do one more thing?  Try running: 

```
import os
os.environ["GRAPHLAB_LAMBDA_WORKER_DEBUG_MODE"] = "1"
os.environ["GRAPHLAB_LAMBDA_WORKER_LOG_FILE"] = r"C:\Users\nijogl\Desktop\lambda_log_file.txt"
os.environ["OMP_NUM_THREADS"] = "1"
import sframe
sframe.SArray(range(1000)).apply(lambda x: x).sum()
```

This should produce two log files on your desktop named lambda_log_file.txt and lambda_log_file.txt-init.  Could you send those to me?  Or tell me if they are not there?  

Thanks so much for your help!  Really appreciate it.
-- Hoyt

**Comment by nikhilrj** [comment]
No problem! Here they are:

[lambda_log_file.txt-init.txt](https://github.com/dato-code/SFrame/files/173058/lambda_log_file.txt-init.txt)
[lambda_log_file.txt](https://github.com/dato-code/SFrame/files/173059/lambda_log_file.txt)

**Comment by hoytak** [comment]
Thank you.  This is really helpful.  We're looking into it now.

**Comment by hoytak** [comment]
Hello Nikhilrj, 

You have some very strange errors.  Windows has a limited number of interprocess shared memory sockets -- what we use to communicate with the lambda workers -- and it appears that something is hanging around and locking these sockets, seemingly previously started lambda workers that were not correctly terminated (correct parent-child process management on windows is horrendously difficult compared to linux or unix).  The interprocess initialization tries to free these processes, fails to do so, and then fails, possibly as a result, causing the lambda workers to then fail.  I'm not sure what got things to this state, but there are a couple things that may help. 

Two things to try:  

1.  Try setting the temporary directory to something else.  This may not fix it, but I'm curious if it does.  This code segment may help with this -- if you could run that and report back, that would be helpful.  (also, the accompanying server log would be great as well). 

```
import os
os.environ["GRAPHLAB_LAMBDA_WORKER_DEBUG_MODE"] = "1"
os.environ["GRAPHLAB_LAMBDA_WORKER_LOG_FILE"] = r"C:\Users\nijogl\Desktop\lambda_log_file_2.txt"
os.environ["GRAPHLAB_CACHE_FILE_LOCATIONS"] = r"C:\Users\nijogl\Desktop\sframe-temp-dir"
os.environ["OMP_NUM_THREADS"] = "1"
import sframe
sframe.SArray(range(1000)).apply(lambda x: x).sum()
```

2.  Rebooting the machine.  This may fix things by cleaning up these crashed processes and their locks on the shared memory sockets.  But if you can't do that, we'll keep looking at this. 

Thanks so much!
-- Hoyt

**Comment by nikhilrj** [comment]
Hello @hoytak,

We scheduled a restart for the machine and it did solve the problem! The lambda workers appear to be  working now.

However, I'm running into another blocking issue using lambdas now. I'm trying to run the following code:

```
import sframe as sf
data = sf.load_sframe('my_data')
result = data.apply(lambda x: x+=1)
len(result)
```

It's worth mentioning the issues I've talked about in this thread are running on a 32 core, 512gb ram Windows Server 2012 machine. When I try to run the code above, I see some CPU and memory activity, but the `len(result)` operation never finishes. I know this code works, as I've executed it on a local machine (4 core, 8gb ram laptop) and it runs without hitch in ~1 minute. The `data` loaded is about ~500mb (10551564 rows x 7 columns) in the SFrame binary format. 

Do you have any guidance on this issue? Thanks again for the support!

**Comment by ylow** [comment]
There is a large perf regression with Lambda's in 1.8.4 (See #226). This has been fixed. We will be putting up 1.8.5 shortly to resolve this. Thanks!

**Comment by hoytak** [comment]
Hello @nikhilrj, 

Thanks for the information.  

Hmm.  Glad to hear the lambda worker issue was (partially) resolved.  We are releasing an updated version

**Comment by nikhilrj** [comment]
Thanks @ylow @hoytak!

**Comment by abiosa** [comment]
@hoytak I appreciate your input but non of these suggestions has helped me in any way. I have been held back with this problem for over 2 weeks. I have a windows 10 system with 8gb ram 64 bit. Does it have anything to do with the problem?
"Lambda workers cannot not start"
Please advise

Thanks

**Comment by niteshnitgupta** [comment]
I am also having the same issue. Even I am not able to resolve this issue. I tried all possible ways suggested above. Can anyone please help me

**Comment by TobyRoseman** [comment]
@niteshnitgupta - The readme for this repository says:
```
THIS REPOSITORY IS DEPRECATED.

THE FUNCTIONALITY HAS MOVED TO Turi Create.
```
See the [Turi Create Repository](https://github.com/apple/turicreate). Turi Create contains all the functionality of this repository and should not have this issue.
