### ISSUE TITLE
Can't import graphlab in IPython notebook

### ISSUE THREAD

**Issue by shenpengjianke** [dato-code/SFrame#243]
Experiment: Mac OS 10.10.2.
I install graphlab by `pip install`.
And I can use graphlab in python and IPython.
But when I import graphlab in IPython Notebook, I just get this:
**In[*] import graphlab**, Not like **In[1] import graphlab**.
What can I do? Please help me out.

**Comment by TobyRoseman** [comment]
@shenpengjianke - What package did you pip install? This is the SFrame repository. If you pip installed SFrame, you should `import sframe` rather than `import graphlab`.

If your question is related to graphlab rather than sframes, please post here: http://forum.dato.com/
