### ISSUE TITLE
Should SFrame.remove_column and DataFrame.drop be equivalent?

### ISSUE THREAD

**Issue by paulochf** [dato-code/SFrame#246]
I'm using SFrame here and I realized that remove_column is not equivalent to DataFrame.drop, as stated [in Dato's Graphlab Create translator](https://dato.com/learn/translator/) "Remove a column from a data table".

There says the two above are equivalent

```
sf.remove_column('new')
df = df.drop('new', axis=1)	
```

, which definitely are, but from two different behaviours.

[df.drop](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html) has an argument `inplace`, in which `True` has similar behaviour to `remove_column`.

The converse is not true: I guess there's no way to remove some columns from a SFrame view/computation without selecting them explicitly like `sf[3:7][['A', 'C']]`. In cases where there's a lot of columns, but just don't want a few of them, a `.drop` would be nicer than the former, and that's a useful feature `df.drop` has that `sf.remove_column` doesn't have.

So I ask:

1. Is this the desirable behaviour for `sf.remove_column`?
2. Would it not be better if one could choose if the passed column should be dropped (like `inplace=True`) or just a view is returned?
3. Is there any other way to do this I may have not thought?

Thanks!

**Comment by TobyRoseman** [comment]
@paulochf -

1 - Yes, it's the desired behavior.
2 - This is something we have talked about. One thing to keep in mind is that SArrays are immutable. So copying a SFrame is very lightweight: the same underlying SArrays are used in both. 
3 - I'm not totally clear on what exactly you're trying to do. If you want two SFrame that are the same except one column has been removed in one of the SFrame, you could do:
```python
import sframe
sf1 = sframe.SFrame({'a': [1,2,3], 'b': ['x','y','z']})
sf2 = sf1.copy()
sf1.remove_column('a')
```

In the future, it's better to post questions like these here: http://forum.dato.com/
You'll also get a faster response.
