### ISSUE TITLE
Sframe in Windows 

### ISSUE THREAD

**Issue by arita291** [dato-code/SFrame#252]
Hi,

When installing sframe in Python, I got this message:

Installing collected packages: requests, tornado, sframe
  Found existing installation: requests 2.8.1
    Uninstalling requests-2.8.1:
      Successfully uninstalled requests-2.8.1
  Found existing installation: tornado 4.2.1
    Uninstalling tornado-4.2.1:
      Successfully uninstalled tornado-4.2.1
  Rolling back uninstall of tornado

    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'd:\\_devs\\python01\\winpython-64-2710\\python-2.7.10.amd64\\lib\\site-packages\\tornado\\speedups.pyd'

How can I prevent the installation of tornado ?

**Comment by esamanas** [comment]
I don't think you can prevent the installation of tornado...I believe it is listed as one of the requirements of SFrame (though I can't remember why).

If I recall correctly, the installation still goes through if the speedups fail to compile, is that right? If you don't want your previously installed versions of packages uninstalled when SFrame gets installed, consider using virtualenv or `conda env` if you are using Anaconda Python.

**Comment by arita291** [comment]
Hi,

Am using WinPython which have a lot of pre-installed packages and has much smoother installed process for deep learning.

Tornado is already pre-installed,

Tornado is used for the communication ZMQ (server).

How Can I install Sframe only (if I have already other packages already installed) ?


Reason is I have to combine Sframe with many many other packages (including),
so virtual env is not a solution (I need to install on the main part).










On 08 Apr 2016, at 06:02, Evan Samanas <notifications@github.com> wrote:

I don't think you can prevent the installation of tornado...I believe it is listed as one of the requirements of SFrame (though I can't remember why).

If I recall correctly, the installation still goes through if the speedups fail to compile, is that right? If you don't want your previously installed versions of packages uninstalled when SFrame gets installed, consider using virtualenv or conda env if you are using Anaconda Python.

―

**Comment by esamanas** [comment]
virtualenv has a flag called `--system-site-packages` that will install all the packages in WinPython in to a new environment you create. That way installing SFrame will at least not try to change the versions of packages in your main environment. I'd still recommend that...Python can get pretty nasty if you don't use virtual environments from my experience. Even if you just have one "main" virtual environment where you install everything, you can at least throw it away at any time and not do harm to your main installation.

Is the installation of SFrame actually failing here? If so, can you please post the entire output?

**Comment by esamanas** [comment]
Closing for now because of inactivity. Feel free to open again if there's more to say.
