### ISSUE TITLE
SArray/SFrame suport for subtracting datetime.datetime and datetime.timedelta

### ISSUE THREAD

**Issue by Kevin-McIsaac** [dato-code/SFrame#259]
I'm working on calculating Customer Lifetime Value and need to compute the differences between the End and Start dates for each row in an SFrame. I noticed subtracting two datetime SArrays is not permitted , i.e., the following shorthand does not work.

           customer['Period'] = customer['End'] - customer['Start'] 

So I thought I'd do it longhand using apply, but SFrame does not accept datetime.timedelta, i.e., the following does not work.

              customer['Period'] = customer.apply(lambda row: customer['End'] - customer['Start'] )

My suggestion is to 
1. Support the shorthand of subtracting two dates
2. Allow an SArray or SFrame column to hold a datetime.timedelta.

**Comment by ylow** [comment]
Added support for subtracting two dates. Returns a float column of seconds.

**Comment by Kevin-McIsaac** [comment]
ylow, for #259, to remove confusion and simplify usage I feel SFrame should follow standard Python semantics for dates, i.e., the difference of two datetime columns/scalars should be a timedelta and the addition of a datetime column/scalar to a timedelta column/scalar should be a datetime.

**Comment by ylow** [comment]
SFrames only support a small set of datatypes and not all Python types. This is by design since we need to maintain efficient interpretation of the types in C++, compression, etc. As such adding support for a new type is non-trivial.
