### ISSUE TITLE
Python 3 import errors after clean install

### ISSUE THREAD

**Issue by hershaw** [dato-code/SFrame#265]
On python 3.4 with an Ubuntu 14.04 machine I create a virtual environment, install `sframe` via `pip` and when I import sframe I get the following:

```
(benchmarks-tmp)jj@sframe-8:~$ uname -a
Linux sframe-8 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
(benchmarks-tmp)jj@sframe-8:~$ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sframe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jj/.virtualenvs/benchmarks-tmp/lib/python3.4/site-packages/sframe/__init__.py", line 42, in <module>
    from .toolkits._model import Model, CustomModel, load_model
  File "/home/jj/.virtualenvs/benchmarks-tmp/lib/python3.4/site-packages/sframe/toolkits/_model.py", line 19, in <module>
    from .. import _gl_pickle
  File "/home/jj/.virtualenvs/benchmarks-tmp/lib/python3.4/site-packages/sframe/_gl_pickle.py", line 11, in <module>
    from .util import _get_aws_credentials as _util_get_aws_credentials, \
  File "/home/jj/.virtualenvs/benchmarks-tmp/lib/python3.4/site-packages/sframe/util/file_util.py", line 18, in <module>
    import boto
  File "/home/jj/.virtualenvs/benchmarks-tmp/lib/python3.4/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/home/jj/.virtualenvs/benchmarks-tmp/lib/python3.4/site-packages/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/home/jj/.virtualenvs/benchmarks-tmp/lib/python3.4/site-packages/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/home/jj/.virtualenvs/benchmarks-tmp/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/jj/.virtualenvs/benchmarks-tmp/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "/usr/share/google/boto/boto_plugins/compute_auth.py", line 18, in <module>
    import urllib2
ImportError: No module named 'urllib2'
>>> 
```

In the same virtual environment with pandas installed, I get a slightly different error:

```
(benchmarks)jj@sframe-8:~/benchmarks$ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sframe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jj/.virtualenvs/benchmarks/lib/python3.4/site-packages/sframe/__init__.py", line 42, in <module>
    from .toolkits._model import Model, CustomModel, load_model
  File "/home/jj/.virtualenvs/benchmarks/lib/python3.4/site-packages/sframe/toolkits/_model.py", line 19, in <module>
    from .. import _gl_pickle
  File "/home/jj/.virtualenvs/benchmarks/lib/python3.4/site-packages/sframe/_gl_pickle.py", line 11, in <module>
    from .util import _get_aws_credentials as _util_get_aws_credentials, \
  File "/home/jj/.virtualenvs/benchmarks/lib/python3.4/site-packages/sframe/util/file_util.py", line 18, in <module>
    import boto
  File "/home/jj/.virtualenvs/benchmarks/lib/python3.4/site-packages/boto/__init__.py", line 1045, in <module>
    boto.plugin.load_plugins(config)
AttributeError: 'module' object has no attribute 'plugin'
>>> 
(benchmarks)jj@sframe-8:~/benchmarks$ pip freeze
SFrame==1.8.5
awscli==1.6.2
bcdoc==0.12.2
boto==2.33.0
botocore==0.73.0
certifi==2015.04.28
colorama==0.2.5
decorator==3.4.0
docutils==0.12
jmespath==0.5.0
multipledispatch==0.4.8
numpy==1.11.0
pandas==0.18.0
prettytable==0.7.2
pyasn1==0.1.9
python-dateutil==2.5.2
pytz==2016.3
requests==2.9.1
rsa==3.1.2
six==1.10.0
tornado==4.1
```

As a quick hack for now, I'm placing a file called `urllib2.py` on my import path which only contains the following:

```
import urllib.request as urllib2
```

Note: on OS X 10.6 this is not an issue.

**Comment by esamanas** [comment]
I've replicated your environment and import works okay for me, in both the pandas and not-pandas case. It looks like both of your errors are originating from boto. Our versions of boto match, so I can only guess that the installation of that package somehow got corrupted? Could you try uninstalling and reinstalling boto==2.33.0?

**Comment by hershaw** [comment]
Thanks! A bit of extra missing context is that this is running on google compute engine. A closer look at the first stack trace shows an attempted import at what looks like a boto GCE plugin:

```
  File "/usr/share/google/boto/boto_plugins/compute_auth.py", line 18, in <module>
    import urllib2
ImportError: No module named 'urllib2'
```

There's a global boto config file in `/etc/boto.cfg` that sets a global plugin directory to `/usr/share/google/boto/boto_plugins` which has the python-2 style import. Looking at the [boto readme](https://github.com/boto/boto) they say that they don't support python 3.x so the failing behavior makes sense I think.

However, if I `pip install boto3` and then `import boto3`, everything works fine. Also, I think that `boto3` is compatible with python 2.7 and 3.x.

Now sure if / how much different the `boto` and `boto3` APIs are, but it seems that since `sframe` supports python 3.4, it should use `boto3` because otherwise, arbitrary `boto` plugins could be loaded which are not backward compatible.

**Comment by esamanas** [comment]
Yeah, so far I don't know of any problems (other than this one) that we've hit with the combination of Python 3.4 and boto 2.33. It appears boto2 had been sort of incorporating Python 3.3 and 3.4 support and then boto3 was made? So it seems like boto 2.33 won't completely break on Python 3.4, but some versions of boto2 will run in to problems. More problems are inevitable as time passes.

So yeah, we should switch to boto3. I don't know how different the APIs are either. This may take a bit of time to complete. I'll bring it up and see if we can get it on someone's priority list.

**Comment by TobyRoseman** [comment]
I agree we should switch to boto3.

At least officially, boto doesn't support python past 3.4: http://boto.readthedocs.org/en/latest/porting_guide.html

The boto package also has not been updated in over a year: https://pypi.python.org/pypi/boto

**Comment by hershaw** [comment]
It seems like the apis are quite different between boto and boto3, definitely not a drop-in replacement. [This migration guide](https://boto3.readthedocs.org/en/latest/guide/migration.html) says that since boto and boto3 can be used alongside each other they recomment a piecemeal approach. However, in the GCE case, this wouldn't help until the migration is complete.

In the meantime, would it be a possibility to use sframe without boto installed? I know I've used packages like that before, where 3rd party extension functionality is opt-in.

I think the takeaway here is that anyone who uses python 3 on GCE and tries to use sframe will not be able to. Furthermore, anyone who has global boto plugins that does python-3 incompatible things will have the same problem.

How involved is the boto usage in general here? I might have a bit of time to make a pass on it in a few weeks.

**Comment by TobyRoseman** [comment]
@hershaw -- apologizes for not responding earlier.

It would be possible to use SFrame without boto install, you would need to remove that dependency from setup.py, just remove this line: https://github.com/dato-code/SFrame/blob/master/oss_src/unity/python/setup.py#L157

Of course if you did that then when anyone tries to use something that depended on boto, they would get an error. So this isn't a change we would want to make to the product.

We're using boto for a lot of functionality, but pretty much all of the usage goes through `file_util.py`: https://github.com/dato-code/SFrame/blob/master/oss_src/unity/python/sframe/util/file_util.py

So the changes to use boto3 may not be too invasive.

Once again sorry for taking so long to respond. Let me know if you have more questions. I'll do my best to get you answers.

**Comment by hershaw** [comment]
Thanks @TobyRoseman. No worries for right now because we've switched to Amazon AWS so things are running better in general now...

However, I think it's a good idea to start a migration toward `boto3`. I think I would like to attempt to migrate at least a portion of the `boto` usage `file_util.py`. Is it unit tested? Do you have any recommendations on where to start?

**Comment by TobyRoseman** [comment]
It is unit tested: https://github.com/dato-code/SFrame/blob/master/oss_src/unity/python/sframe/test/test_file_util.py

Here are the things I would do:
1 - change the line in `setup.py`, that I mentioned earlier, to use boto3 rather than boot.
2 - modify `file_util.py` to use the new API.
3 - Make sure the the unit test still pass.
4 - The only other place we seem to be using boto is here https://github.com/dato-code/SFrame/blob/master/oss_src/unity/python/sframe/test/test_gl_pickler.py#L224

**Comment by hershaw** [comment]
Excellent, thanks for the info!

Curious, why the fallback on [aws cli](https://github.com/hershaw/SFrame/blob/master/oss_src/unity/python/sframe/util/file_util.py#L239)? Would be nice to just make `boto3` a requirement and not have to support manual executions of commands.

**Comment by TobyRoseman** [comment]
I believe the reason is that aws cli uses multi-part upload/download. It's required for when we have to work with large files.

**Comment by hershaw** [comment]
Going to close this thread and open another issue for boto -> boto3 migration
