### ISSUE TITLE
Unexpected behavior with boolean masks on columns with null values

### ISSUE THREAD

**Issue by hershaw** [dato-code/SFrame#270]
When looking to drop all rows in an SFrame for all columns that contain a certain value I do the following:

```
import sframe

sf = sframe.SFrame({
    'col1': ['a', 'b', None],
    'col2': ['d', 'e', 'f'],
})

mask = sf['col1'].apply(lambda x: x != 'a')
sf_with_dropped = sf[sf['col1'].apply(lambda x: x != 'a')]

print(sf_with_dropped)
print(mask)
```

Produces the output:
```
+------+------+
| col1 | col2 |
+------+------+
|  b   |  e   |
+------+------+

[? rows x 2 columns]
Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
You can use len(sf) to force materialization.
[0, 1, None]
```

I would expect that only the first row would be dropped but since the null value is not replaced with a 0 or 1, the mask contains a falsy value which causes the extra column to be dropped.

**Comment by ylow** [comment]
apply takes an optional argument "skip_undefined" which defaults to true. You can instead use:
```
mask = sf['col1'].apply(lambda x: x != 'a', skip_undefined=False)
```

**Comment by hershaw** [comment]
Thanks. Any particular reason for the opt-in behavior? It's quite a departure from the norm.

**Comment by ylow** [comment]
The idea is to avoid having people write things like

```
sa.apply(lambda x: blah if x is not None else None)
```

It was not necessarily the best design decision. But now that it has been made it is not so easy to revert.

**Comment by hershaw** [comment]
No worries, just wondering if there were performance reasons or something. Maybe it could be up for the next major version, it's quite a gotcha for those of us coming from pandas.

thanks
