### ISSUE TITLE
Conversion to Spark dataframe duplicates some rows and looses others

### ISSUE THREAD

**Issue by nicoinn** [dato-code/SFrame#312]
Hi!

I have noticed a strange bug while converting SFrames to Spark Dataframes: in some rare cases, a few lines of the SFrame become duplicated, while the total number of rows remains the same (thus some get lost). 
The problem happens only when requesting a distributed dataframe. 

Code for reproducing the issue: 

----------------

import sframe
sf_test = sframe.SFrame.read_csv('./data/test.csv')
print len(sf_test)   #Should print  75818
print len(sf_test[sf_test["ID"]==75811])  #Should print 1

import findspark
findspark.init()
import pyspark
sc = pyspark.SparkContext()  
from pyspark.sql import SQLContext
from pyspark.sql.types import *
sqlContext = SQLContext(sc)

spark_test = sf_test.to_spark_dataframe(sc,sqlContext,4)  #<=== If 4 is used, duplication happens, if 1, everything is ok.
sf_test_back = sframe.SFrame(spark_test.toPandas())
print len(sf_test_back) #Should print  75818
print len(sf_test_back[sf_test_back["ID"]==75811])  #Should print 1, prints 2!

----------------

The test.csv file is taken from here: https://www.kaggle.com/c/santander-customer-satisfaction/data

**Comment by esoroush** [comment]
Hi Nicolas, Thanks for reporting this issue. It's a bug deep in our partitioning mechanism. I will let you know when we fix is ready.

**Comment by TobyRoseman** [comment]
@esoroush - can this issue be closed?

**Comment by esoroush** [comment]
This issue is resolved
