### ISSUE TITLE
Compile as dynamic library?

### ISSUE THREAD

**Issue by malmaud** [dato-code/SFrame#32]
Is there a supported set of configuration options to compile dynamic instead of static libraries? 

The context here is I'm trying to write an in-process wrapper for SFrames for the Julia programming language, which will require loading the graphlab libraries at runtime.

**Comment by chrisdubois** [comment]
There should be a dynamic library already available when you build inside of `debug/` or `release/`.

I was able to get it loaded using Cxx.jl, but this is as far as I got. 

```using Cxx
addHeaderDir("/Users/chris/SFrame/oss_src", kind=C_System)
addHeaderDir("/Users/chris/SFrame/deps/local/include", kind=C_System)
Libdl.dlopen("/Users/chris/SFrame/debug/oss_src/unity/libunity_shared.dylib", Libdl.RTLD_GLOBAL)
cxxinclude("/Users/chris/SFrame/oss_src/unity/lib/gl_sarray.hpp")
cxxinclude("/Users/chris/SFrame/oss_src/unity/lib/gl_sframe.hpp")
cxxinclude("/Users/chris/SFrame/oss_src/flexible_type/flexible_type.hpp")


icxx"""
graphlab::gl_sframe a = graphlab::gl_sframe();
a["hello"] = graphlab::gl_sarray::from_sequence(0,1000);
a["world"] = 2;
a["world"] = a["world"] + 5;
std::cout << a;
"""

x = @cxxnew graphlab::gl_sarray::from_sequence(0, 500)```

**Comment by malmaud** [comment]
Ah, great. Thanks for clarifying.
