### ISSUE TITLE
Python Lambda Execution Robustness

### ISSUE THREAD

**Issue by ylow** [dato-code/SFrame#33]
The current mode of python lambda parallelization involves spinning of a collection of subprocesses (pylambda_worker) each of which is dynamically linked to libpython.so. These pylambda_workers then connect back to the original process via interprocess shared memory.

This causes issues in certain situations :
 - There are multiple python versions, in which case we may pick up the wrong libpython. (We conflict *really* badly on Mac when there is brew python as well as system python)
 - Some self-built python installations on Linux in particular do not build libpython.so

The proposal is to flip the linking around.
 - instead of spinning of pylambda_workers, we spin off python processes.
 - These python processes then use ctypes to load a pylambda_worker *shared library* and call into it
This way we resolve our python symbols via python itself. 
 - Change pylambda

**Comment by tristanz** [comment]
This issue affects GraphLab on Sense, so I'm +1 on to this.

**Comment by hoytak** [comment]
@tristanz: Thank you for the +1; I'm looking in to this.

**Comment by hoytak** [comment]
This should be addressed by https://github.com/dato-code/SFrame/pull/43.  If there are any further issues with this, let's open up a new issue.
