### ISSUE TITLE
Memory Size Detection

### ISSUE THREAD

**Issue by ylow** [dato-code/SFrame#34]
Currently, we try to autotune the amount of memory we use by detecting the amount of system memory. However, this is problematic when we are run inside of docker since we detect the total amount of memory on the system (via sysinfo), rather the amount of memory allocated to us. (See http://fabiokung.com/2014/03/13/memory-inside-linux-containers/, https://github.com/docker/docker/issues/12394)

As of docker 1.8 which is rather new, we should be able to look into /sys/fs/cgroups or /proc/self/cgroup or something like that. But not everyone will be on docker 1.8, so we need an API workaround as well.

 - Use /sys/fs/cgroups to determine our memory limit and use that
 - ?Alternatives?
 - Add an sframe.set_memory_limit function that auto-configures the memory limit based on what the user tells us. This is the ultimate fallback.

**Comment by hoytak** [comment]
Can this issue be closed?

**Comment by shardool-freightwalla** [comment]
@ylow  Can you please elaborate how we can explicitly mention the sframe memory usuage. Couldn't find any definition about it.

I am getting the below error when i try to filter an sframe on heroku server. Locally it works perfect. The sframe size is < 1MB. I am unable to recreate it on heroku as manually running the same code works on heroku bash, so cant provide a reproducible code to demonstrate.

heroku stack :

Linux 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
RAM 512 MB

     *** Error in `python': double free or corruption (out): 0x00007fac2389c030 ***

ps: The app was working fine when used graphlab Sframe , but the open source gives the memory error. Attached logs.
[sframe_server_1469266810.txt](https://github.com/turi-code/SFrame/files/379494/sframe_server_1469266810.txt)

Hoping that setting the memory would help here.

**Comment by shardool-freightwalla** [comment]
Runtime config if that helps.

     app[worker.1]: {'GRAPHLAB_FILEIO_ALTERNATIVE_SSL_CERT_DIR': '', 'GRAPHLAB_SFRAME_IO_READ_LOCK': 0, 'GRAPHLAB_FILEIO_MAXIMUM_CACHE_CAPACITY_PER_FILE': 16106591232, 'GRAPHLAB_FORCE_IPC_TO_TCP_FALLBACK': 0, 'GRAPHLAB_SGRAPH_TRIPLE_APPLY_EDGE_BATCH_SIZE': 1024, 'GRAPHLAB_SGRAPH_TRIPLE_APPLY_LOCK_ARRAY_SIZE': 1048576, 'GRAPHLAB_SGRAPH_HILBERT_CURVE_PARALLEL_FOR_NUM_THREADS': 8, 'GRAPHLAB_CACHE_FILE_HDFS_LOCATION': '', 'GRAPHLAB_FILEIO_INSECURE_SSL_CERTIFICATE_CHECKS': 0, 'GRAPHLAB_SFRAME_DEFAULT_NUM_SEGMENTS': 8, 'GRAPHLAB_SGRAPH_DEFAULT_NUM_PARTITIONS': 8, 'GRAPHLAB_SGRAPH_INGRESS_VID_BUFFER_SIZE': 1048576, 'GRAPHLAB_ODBC_BUFFER_SIZE': 3221225472, 'GRAPHLAB_LAMBDA_WORKER_CONNECTION_TIMEOUT': 60.0, 'GRAPHLAB_USE_GL_DATATYPE': 0, 'GRAPHLAB_SFRAME_MAX_LAZY_NODE_SIZE': 10000, 'GRAPHLAB_SFRAME_JOIN_BUFFER_NUM_CELLS': 125832744, 'GRAPHLAB_SFRAME_DEFAULT_BLOCK_SIZE': 65536, 'GRAPHLAB_FILEIO_ALTERNATIVE_SSL_CERT_FILE': '/app/.heroku/python/lib/python2.7/site-packages/certifi/cacert.pem', 'GRAPHLAB_SFRAME_WRITER_MAX_BUFFERED_CELLS': 33554432, 'GRAPHLAB_SFRAME_WRITER_MAX_BUFFERED_CELLS_PER_BLOCK': 262144, 'GRAPHLAB_SFRAME_READ_BATCH_SIZE': 128, 'GRAPHLAB_CACHE_FILE_LOCATIONS': '/var/tmp', 'GRAPHLAB_SFRAME_MAX_BLOCKS_IN_CACHE': 128, 'GRAPHLAB_SFRAME_CSV_PARSER_READ_SIZE': 52428800, 'GRAPHLAB_DEFAULT_NUM_GRAPH_LAMBDA_WORKERS': 16, 'GRAPHLAB_GLOBALS_PYTHON_EXECUTABLE': '/app/.heroku/python/bin/python', 'GRAPHLAB_SFRAME_GROUPBY_BUFFER_NUM_ROWS': 25166548, 'GRAPHLAB_LIBODBC_PREFIX': '', 'GRAPHLAB_DEFAULT_NUM_PYLAMBDA_WORKERS': 16, 'GRAPHLAB_SFRAME_SORT_BUFFER_SIZE': 8053295616, 'GRAPHLAB_SFRAME_SORT_PIVOT_ESTIMATION_SAMPLE_SIZE': 2000000, 'GRAPHLAB_SFRAME_SORT_MAX_SEGMENTS': 768, 'GRAPHLAB_SGRAPH_BATCH_TRIPLE_APPLY_LOCK_ARRAY_SIZE': 1048576, 'GRAPHLAB_ODBC_BUFFER_MAX_ROWS': 2000, 'GRAPHLAB_FILEIO_MAXIMUM_CACHE_CAPACITY': 16106591232, 'GRAPHLAB_SFRAME_FILE_HANDLE_POOL_SIZE': 3072}

**Comment by shardool-freightwalla** [comment]
@ylow On more digging about the core issue i was able to create a reproducible sample as below. Issue doesn't seem to be of memory but how sframes handles unicode.

    ~ $ cat  tests/sframe_example.py 
     from sframe import SFrame

     def sframe_example():

          print 'Sframe started'
    
          edges = SFrame({'source': [1, 2, 3], 'dest': ['abc', 'def', 'zyx']})

          abc = unicode('abc', 'utf_8')

          edges = edges.filter_by(abc, 'dest')

          print edges

     sframe_example()

~ $ python tests/sframe_example.py 
    Sframe started
    [INFO] sframe.cython.cy_server: SFrame v2.1 started. Logging           /tmp/sframe_server_1469435766.log
*** Error in `python': free(): invalid pointer: 0x00007f83b41410c0 ***
      Aborted

Please note the issue is seen only in heroku environment and not on my local. If you need any more information pls let me know. Also this works fine with Graphlab sframes on heroku.
