### ISSUE TITLE
current built fails on ubuntu 16.04

### ISSUE THREAD

**Issue by franklingu** [dato-code/SFrame#393]
because of ld error

**Comment by TobyRoseman** [comment]
@franklingu  - the readme for this repository says:
```
THIS REPOSITORY IS DEPRECATED.

THE FUNCTIONALITY HAS MOVED TO Turi Create.
```
See the [Turi Create Repository](https://github.com/apple/turicreate). Turi Create contains all of the functionality from this repository and it builds on Ubuntu 16.04.

**Comment by franklingu** [comment]
yes. I just used that and it works perfectly.
