### ISSUE TITLE
Problem in CSV reader

### ISSUE THREAD

**Issue by malmaud** [dato-code/SFrame#41]
[This CSV file](https://www.dropbox.com/s/uf7s750wzh16mzk/batch.csv?dl=1) loads fine with pandas, but seems to choke the SFrame CSV parser:

```
In [24]: df=gl.SFrame.read_csv("batch.csv")
PROGRESS: Unable to parse line ""3Y3N5A7N4F8BFCSGP0QMO7PDF0FYME","26PZ9RNDWIOV420VVL4TLU13ZJYUFK","x","y","z","Fri Oct 09 12:38:00 PDT 2015","20","BatchId:2118345;","2700","604800","Fri Oct 16 12:38:00 PDT 2015","","","31HQ4X3T3S9XZSVFGK2JUSI8Z2RSLJ","A3579N2TITA69M","Submitted","Fri Oct..."
PROGRESS: Unable to parse line ""3Y3N5A7N4F8BFCSGP0QMO7PDF0FYME","26PZ9RNDWIOV420VVL4TLU13ZJYUFK","x","y","z","Fri Oct 09 12:38:00 PDT 2015","20","BatchId:2118345;","2700","604800","Fri Oct 16 12:38:00 PDT 2015","","","32N49TQG3GHWV1LFDOIYW1M44UOVAB","A3BBGFC0RG39HK","Submitted","Fri Oct..."
PROGRESS: 2 lines failed to parse correctly
PROGRESS: Finished parsing file /Users/malmaud/tmp/batch.csv
PROGRESS: Parsing completed. Parsed 0 lines in 0.010217 secs.
Insufficient number of rows to perform type inference
Could not detect types. Using str for each column.
PROGRESS: Unable to parse line ""3Y3N5A7N4F8BFCSGP0QMO7PDF0FYME","26PZ9RNDWIOV420VVL4TLU13ZJYUFK","x","y","z","Fri Oct 09 12:38:00 PDT 2015","20","BatchId:2118345;","2700","604800","Fri Oct 16 12:38:00 PDT 2015","","","31HQ4X3T3S9XZSVFGK2JUSI8Z2RSLJ","A3579N2TITA69M","Submitted","Fri Oct..."
PROGRESS: Unable to parse line ""3Y3N5A7N4F8BFCSGP0QMO7PDF0FYME","26PZ9RNDWIOV420VVL4TLU13ZJYUFK","x","y","z","Fri Oct 09 12:38:00 PDT 2015","20","BatchId:2118345;","2700","604800","Fri Oct 16 12:38:00 PDT 2015","","","32N49TQG3GHWV1LFDOIYW1M44UOVAB","A3BBGFC0RG39HK","Submitted","Fri Oct..."
PROGRESS: 2 lines failed to parse correctly
PROGRESS: Finished parsing file /Users/malmaud/tmp/batch.csv
PROGRESS: Parsing completed. Parsed 0 lines in 0.01067 secs.
```

**Comment by ylow** [comment]
We need better CSV error reporting, but essentially the two data lines have three fewer columns than the header. We intentionally fail on this case. Pandas parser by default will pad with NaN values. (if you look at the output of the pandas parse).

**Comment by malmaud** [comment]
Thanks!

**Comment by ylow** [comment]
Sorry, if I was unclear. I am not sure if I intend to fix this. Pandas pad with NaN values, but I am not sure if that is sensible. I feel like in this case it is a bad file and failing seems to be the right thing to do.

**Comment by malmaud** [comment]
Ya I understand; was just thanking you for the response. FWIW, my CSV came directly from Amazon’s Mechanical Turk, so I guess they’re serving these malformed CSVs by default.

**Comment by SuperJohn** [comment]
Given this issue, when I'm exporting from an external source to csv, what should I populate the missing values to allow sframe.read_csv to parse those rows and recognize the missing values? Should I put 'NaN' strings in there?

**Comment by sachika11** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/67162589/85205070-6017cd80-b336-11ea-8b67-faa5599d3ee8.png)
how to solve this error.
