### ISSUE TITLE
PyLambda worker testing.

### ISSUE THREAD

**Issue by hoytak** [dato-code/SFrame#66]
The pylambda workers allow efficient parallel execution of functions over sframe and sarray type, but they have been historically plagued by library resolution issues and linking issues.  The previous pull request should fix all of these issues.   The primary idea is that it spawns separate processes of the python interpreter, which then loads the pylambda workers as a library and by file, instead of as a separate process linked to libpython.   Both of these things are reliably determined at startup, whereas libpython is not. 

To ensure that this change indeed works, we need to test that it runs on a number of different configurations and systems.  

To sign off on this feature, we need to make sure that `nosetests .../sframe/test/test_lambda_workers.py` 
runs on the following systems:

- [x] Linux
- [x] Linux, installed with sudo into system environment. 
- [x] Linux, ran with older python version manually installed and not on system path 
- [x] Linux: sframe package loaded and server started, then downgrade python so older python is now in the system path, then start pylambda workers. 
- [x] Linux inside a virtualenv.
- [x] Linux inside a conda environment with different python versions installed.

- [x] CentOS 6 (use AWS machine), with python 2.7 installed manually through yum, with /usr/bin/python symlinked to python 2.6
- [x] CentOS 6, with python 2.7 installed manually through yum, with /usr/bin/python symlinked to python 2.7 (who would do this...)
- [x] CentOS 6, with virtualenv. 

- [x] Mac OSX (10.8, 10.9, 10.10).  Any combination of brew installed python, anaconda installed python, and system installed python.  (Just report what you've tested).

- [x] Windows 7. 
- [x] Windows with old python27.dll in C:\windows\system32\ and/or C:\windows\syswow64.  Install old versions (2.7.6 or earlier) of both 32bit and 64bit python from python.org.  Test using new version of anaconda.
- [x] Windows with a space in the user name.
- [x] Windows with python installed into a path with spaces in it.

**Comment by hoytak** [comment]
@ylow @esamanas @haijieg:  With all the internal testing we've done on this, I'm going to signoff on this and close this issue unless more problems arise.  Objections?

**Comment by esamanas** [comment]
No objections. All the testing I did with GraphLab Create I also did with the SFrame build.
