### ISSUE TITLE
C++ API for read_csv

### ISSUE THREAD

**Issue by malmaud** [dato-code/SFrame#74]
I can't seem to find how to load an SFrame from a CSV using the C++ API. Can you point me in the right direction?

**Comment by ylow** [comment]
There are 2 possible entry points.

One is to invoke the parser directly. See https://github.com/dato-code/SFrame/blob/master/oss_src/unity/lib/unity_sframe.cpp#L125 or even the parser test https://github.com/dato-code/SFrame/blob/master/oss_test/sframe/sframe_csv_test.cxx for examples.

Alternatively, and the preferred way is the gl_sframe (which tries to match the python entry points). https://github.com/dato-code/SFrame/blob/master/oss_src/unity/lib/gl_sframe.hpp#L517. 

Unfortunately that function seems to be lacking documentation about what the config_map should contain. See https://github.com/dato-code/SFrame/blob/master/oss_src/unity/lib/unity_sframe.cpp#L125 about how that map is unpacked. I should add documentation.

Regarding documentation of gl_sframe / gl_sarray usage itself, they have a lot of doxygen documentation. Here is a generated copy https://dato.com/products/create/sdk/docs/index.html.

**Comment by malmaud** [comment]
Thanks! I have been making use of the doxygen docs, but if you just type 'csv' in its search it comes up empty, prompting my question.

**Comment by ylow** [comment]
Ooo. For some reason the csv aren't generated. Hmm....

**Comment by malmaud** [comment]
Hmm, it seems `construct_from_csvs` is always return 'string' columns unless explicitly given column types with `column_type_hints`. Do I need to do something special to turn on type inference?

**Comment by ylow** [comment]
Hi,

Sorry, the current architecture means that parts of the implementation are in Python (sframe.py) while parts of the implementation are in C++. We intend to move more implementation into the C++ layer, but as you can imagine that is a relatively... low priority task. But this is what you do:

```
// limit parsing to 100 rows. parse all columns with "undefined" type.
csv_config["row_limit"] = 100;
res = sframe.construct_from_csvs(csv_file, csv_config, {{"__all_columns__", flex_type_enum::UNDEFINED}});
```

The result sframe now has each column type UNDEFINED. This is a special column type, and few operators support it, but it basically allows every element to be of a different type. Now we need to infer the types.
```
std::map<std::string, flex_type_enum> column_types;
for(const auto& column_name: sframe.column_names()) {
    auto col = sframe.select_column(column_name);

    std::set<flex_type_enum> types; // types I see in this column
    for (const auto& val: col.range_iterator()) {
        if (val.get_type() != flex_type_enum::UNDEFINED) types.insert(val.get_type());
    }

    // We default to string in all cases.
    flex_type_enum inferred_column_type = flex_type_enum::STRING;
    if (types.size() == 1) inferred_column_type = *(types.begin());
    else if (types.size() == 2) {
        if (types.count(flex_type_enum::INTEGER) && types.count(flex_type_enum::FLOAT)) {
           // a column with both float and integer is a float
           inferred_column_type = flex_type_enum::FLOAT;
        } else if (types.count(flex_type_enum::LIST) && types.count(flex_type_enum::VECTOR)) {
            // a column with both list and vector is a list
           inferred_column_type = flex_type_enum::LIST;
        }
    }
    // All other cases, can't infer type. default to string
    column_types[column_name] = inferred_column_type;
} 

// ok! now reparse all the rest of the file with the inferred types
csv_config.erase("row_limit")
res = sframe.construct_from_csvs(csv_file, csv_config, column_types);
```

(I just wrote the above here in the browser. I cannot be certain if it compiles)
