### ISSUE TITLE
On windows, libpylambda_worker.dll needs manifest to load the correct libraries. 

### ISSUE THREAD

**Issue by hoytak** [dato-code/SFrame#98]
The new libpylambda_worker.dll needs to have an accompanying manifest so that it loads all dependent libraries from the local graphlab directory.  The main issue encountered here is that old openssl libraries are not compatible, and many openssl installers put libraries by default into C:\System32.  Thus if someone has an old version of openssl installed, then the pylambda workers won't start.

**Comment by ylow** [comment]
Can this close?

**Comment by hoytak** [comment]
Yes, fixed.
